language: node_js
node_js:
  - "4"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - oracle-java8-set-default
env:
  - TRAVIS=travis CXX=g++-4.8
before_script:
  - npm install grunt-cli -g
install:
  - npm install
services:
  - mongodb
script:
  - npm test
  - ./ft.sh
