language: node_js
node_js:
- '4'
addons:
  artifacts:
    debug: true
    paths:
    - "./test/functional/screenshots"
    - "*.log"
    target_paths: "$TRAVIS_BUILD_NUMBER"
    working_dir: WORKING_DIR
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - oracle-java8-set-default
env:
  matrix:
  - TRAVIS=travis CXX=g++-4.8
  - ARTIFACTS_BUCKET=travisci-thoughtbnb
  - secure: NOsqDVImWxBr4Cm1oqMf1sl5guJHj9mHyUcX6tYeOmeODlpycplqpi6Usu6eCgB423MUX5sc8bUCFsXhx6SSqeAA4SyIX622MfCYR66izQ3UxqK1A0v4m3c+g67ptRYJn1uvfcxtVKon/NRLNfvzujbzKtqCcAhlg+977YDQ9XsOLsHg30KZ1FVl7+ykBKPTSIBiBVxazXtVULQec7waYayFqAw7+g4fFIRO78Cxxqi3hHUzlTF9lXcvufrIpXAW9ZGdu2z+IVusVd4ED0AwFVNgOBz1ijICMJfP3K9kItrCfxUvsVps3CQI1qw2YaCaTUslQWHYXRT/zz7E7HDdcBq3iOb0Gnt4KYnrEdR8tFLAS1JjPLzoKrWdvCopyF6iQ52+4abd68PTvuRXSyrDZYkQl4GkjHrUG3a0fb2Tduq9OxLDf71hE9pwY8pKDw+iO0Uh/4/J//1+87jDc3I2rhn4T/eO7vlbw9g9rMEwFquuxlC+22tqwRbVlFIEyph9o/t426TQ3ZyleiRcYNGd8EBeuady31N5deA+79AzGUPBOcgGZTs8hUYV8UldLC586lKxBIbLWZ5lP3o9hXyioii2zNlnRei3k5PHP4jx6XdEN2+AYyHWjPXJugv1E7IwUMe6Bqk4X7I+RqypC0MsXu5DgMMvBUDxmgnmAMRcWYE=
  - secure: o7SO/32PyzRxi/uGkH51Fjw4NHf4Dx6NZduSZ3ecfoVWUnfaMV+pXrX/2HpXiopRrn0xyc3mCGMslmEsRZiEigcQSLmlVGExs/BJAk8/OA3Xe1YPcqmGisv7KxlHIUbguOUYyxWwYvZhvNY89UJy+VbtrefW0Zs4mZwQawh4sF27plv9x8jsyi7BAZNbMrNcZpbWvqro+Sl4DsTewjhxFWD7f++FRfEtUkXLlT2vPdO3aVDDZ0zT/zuUmBmhoEvoNl3An1XAKHbZOBB7ETBKWYCA9fIp7dD3Ye3qn3Mta2IggxMt61VOPYlsPectBYo90fg+4LjN4xvJfusHaoVFyiRqT8U+Gtnw2T6uQUFoOBgKuSzo9K42artDlI+O3cZCZAs18eBG2Xl9HuXiCqQ9O1f1zccw5nnJxhNy/Ml2LOB/HdT3xx/llUEFzX1bk0d63pONeRspANFWZT0AS2YbUMweWzSVsigxtpNXFRtKgq1fCmNzFuj9OM+DsbEsZvDMRvKV2GtOhLAGNW38NlHEE8XUekAHabNQVZaJOAUeC1LDFJW5YQxCy3A8SCDHntKZrd9hGcwp7P57WUA03UU69nlijpQCl25xEenwkKeKZK/xSXzXgJbXqCQ1fp8c/f4rvEuLol4++HR0YTEV8YhxBujnw7BxwDmCzshTzR4Fzog=
before_script:
- npm install grunt-cli -g
install:
- npm install
services:
- mongodb
script:
- seed
- npm test
- "./ft.sh"
