version: "2"
services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_DB: mongodb://mongo/thoughtbnb
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
